[package]
name = "webplus-plugin-repository"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile = "3"
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
webplus-plugin-trust.workspace = true

[dev-dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
