[package]
name = "ssdev-origin-policy"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ssdev-config.workspace = true
thiserror.workspace = true
url.workspace = true
webplus-plugin-trust.workspace = true

[dev-dependencies]
base64.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core"] }
tempfile = "3"
