[package]
name = "webplus-plugin-host"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde_json.workspace = true
tokio.workspace = true
webplus-ipc.workspace = true
webplus-native.workspace = true
webplus-plugin-config.workspace = true
webplus-plugin-trust.workspace = true
webplus-protocol.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Pipes"] }
