[package]
name = "ssdev-project-bundle"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ssdev-config.workspace = true
tempfile = "3"
webplus-plugin-config.workspace = true
webplus-plugin-trust.workspace = true
zip.workspace = true

[dev-dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
