[package]
name = "webplus-plugin-package"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
tempfile = "3"
thiserror.workspace = true
tracing.workspace = true
webplus-plugin-config.workspace = true
webplus-plugin-trust.workspace = true
zip.workspace = true

[dev-dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
serde_json.workspace = true
