import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const appVue = new URL('../../apps/desktop/src/App.vue', import.meta.url)
const desktopRust = new URL('../../apps/desktop/src-tauri/src/desktop.rs', import.meta.url)
const commandPermissions = new URL('../../apps/desktop/src-tauri/src/command_permissions.rs', import.meta.url)
const localCapability = new URL('../../apps/desktop/src-tauri/capabilities/local-shell.json', import.meta.url)
const generatedPermission = new URL('../../apps/desktop/src-tauri/permissions/autogenerated/inspect_business_data_clear.toml', import.meta.url)

test('business data clear requires a bound local preview before mutation', async () => {
  const [app, desktop, commands, capabilityDocument, permission] = await Promise.all([
    readFile(appVue, 'utf8'),
    readFile(desktopRust, 'utf8'),
    readFile(commandPermissions, 'utf8'),
    readFile(localCapability, 'utf8'),
    readFile(generatedPermission, 'utf8'),
  ])
  const capability = JSON.parse(capabilityDocument)
  const inspect = app.indexOf("invoke<BusinessDataClearPreview>('inspect_business_data_clear')")
  const confirm = app.indexOf("invoke<BusinessDataClearResult>('clear_business_data'")

  assert.ok(inspect >= 0 && confirm > inspect)
  assert.match(app, /expectedPlanId: preview\.planId/)
  assert.match(app, /Cookie、登录状态、缓存和本地存储不可恢复/)
  assert.match(desktop, /SSDEV-BUSINESS-DATA-CLEAR-PLAN/)
  assert.match(desktop, /preview\.plan_id != expected_plan_id/)
  assert.match(desktop, /caller\.clear_all_browsing_data\(\)/)
  assert.match(desktop, /label\.starts_with\(BUSINESS_LABEL_PREFIX\) \|\| label\.starts_with\(FLOATING_LABEL_PREFIX\)/)
  assert.doesNotMatch(desktop, /"clear-business-data"\s*=>/)
  assert.doesNotMatch(desktop, /\.text\("clear-business-data"/)
  assert.match(commands, /"inspect_business_data_clear"/)
  assert.match(commands, /"allow-inspect-business-data-clear"/)
  assert.ok(capability.permissions.includes('allow-inspect-business-data-clear'))
  assert.ok(capability.permissions.includes('allow-clear-business-data'))
  assert.match(permission, /commands\.allow = \["inspect_business_data_clear"\]/)
})
