import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const appVue = new URL('../../apps/desktop/src/App.vue', import.meta.url)
const desktopRust = new URL('../../apps/desktop/src-tauri/src/desktop.rs', import.meta.url)
const commandPermissions = new URL('../../apps/desktop/src-tauri/src/command_permissions.rs', import.meta.url)
const localCapability = new URL('../../apps/desktop/src-tauri/capabilities/local-shell.json', import.meta.url)
const generatedPermission = new URL('../../apps/desktop/src-tauri/permissions/autogenerated/retry_timed_out_business_windows.toml', import.meta.url)

test('timed out business recovery is targeted and available only to the local console', async () => {
  const [app, desktop, commands, capabilityDocument, permission] = await Promise.all([
    readFile(appVue, 'utf8'),
    readFile(desktopRust, 'utf8'),
    readFile(commandPermissions, 'utf8'),
    readFile(localCapability, 'utf8'),
    readFile(generatedPermission, 'utf8'),
  ])
  const capability = JSON.parse(capabilityDocument)

  assert.match(app, /invoke<BusinessFrontendRetryResult>\('retry_timed_out_business_windows'\)/)
  assert.match(app, /仅重试失败窗口/)
  assert.match(desktop, /claim_timed_out_business_windows\(\)/)
  assert.match(desktop, /restore_business_frontend_timeout\(&label, generation\)/)
  assert.match(desktop, /start_business_frontend_watchdog\(app\.clone\(\), label, generation\)/)
  assert.match(commands, /"retry_timed_out_business_windows"/)
  assert.match(commands, /"allow-retry-timed-out-business-windows"/)
  assert.ok(capability.permissions.includes('allow-retry-timed-out-business-windows'))
  assert.match(permission, /commands\.allow = \["retry_timed_out_business_windows"\]/)
  assert.doesNotMatch(desktop, /business-frontend-retry-failed[^\n]+%/)
})
